### ISSUE TITLE
Support for rendering list links from xwing-builder.co.uk

### ISSUE THREAD

**Issue by ajmath** [FreakyDug/r2-d7#3]
The bot currently supports parsing lists mentioned with https://geordanr.github.io/xwing/ links, but a large majority of users use xwing-builder.co.uk (including list juggler escrow for the vassal league).

I'm currently working on a separate chatbot for league stuff that will eventually include posting messages when a match has been escrowed.  This will likely just post the URLs to the lists they used in the escrow.  If both squad builders are supported, this would enable the league chat bot (lobot) to show the full list contents via r2-d7.

Is there any technical reason this cannot be done or won't be done?  I'd be up for contributing if needed.

Thanks!

**Comment by FreakyDug** [comment]
(Sorry for the delay, apparently yo don't watch your own repos by default)

I looked into this a while ago and the problem I hit was that the xwing-builder links don't encode the list like YASB does, so you need to either scrape the page or get xwing-builder to generate XWS (and then scrape that because it doesn't provide it in an easy to reach API), so you're effectively creating a whole new list printer. It's not impossible, but it's quite a lot of work and I never use xwing-builder (YASB is way better, IMO) so I'm not motivated to do it.

I would absolutely be up for integrating it if someone else wants to do the work.

**Comment by ajmath** [comment]
Cool.  I was looking into the codebase after I made this issue and then realized how closely integrated it was with YASB.  

Looks like xwing-builder.co.uk has XWS export via http://xwing-builder.co.uk/xws/487314?dl=1
I didn't immediately see anywhere on YASB where it can export XWS.

**Comment by FreakyDug** [comment]
Ah-ha, I couldn't find a way to get the XWS outside the HTML page. That would make it easier. 

YASB has an export to XWS button at the bottom of the page, but I don't see a way to just request the XWS.

Writing a separate list printer to parse XWS (maybe using https://github.com/guidokessels/xwing-data rather than the YASB data) and having that respond to xwing-builder links wouldn't be too difficult.

**Comment by ajmath** [comment]
@geordanr is there a way to get XWS from a permalink via an "API" call?

**Comment by geordanr** [comment]
Given a permalink you can get XWS by sending the query string to https://yasb-xws.herokuapp.com

E.g.
[Permalink](https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!8:120,-1,-1,-1:-1:-1:;1:-1,78:-1:-1:;4:-1,70:-1:-1:U.30;45:-1,40:-1:-1:&sn=Anti-Synergy)
[XWS link](https://yasb-xws.herokuapp.com/?f=Rebel%20Alliance&d=v4!s!8:120,-1,-1,-1:-1:-1:;1:-1,78:-1:-1:;4:-1,70:-1:-1:U.30;45:-1,40:-1:-1:&sn=Anti-Synergy)

**Comment by FreakyDug** [comment]
Awesome, thanks @geordanr.

**Comment by FreakyDug** [comment]
I've got this mostly working. It needs some more testing, but should be done this weekend.

**Comment by ajmath** [comment]
Thanks!  This is awesome!
